import { List } from "..";
const myList = new List<string>(["ciao", "mondo", "come", "va", "?"]);
console.log("List.Count: ", myList.Count);
myList.ForEach((x, index) => {
  console.log(`element of number ${index}: ${x}`);
});
console.log("List.ToString(): ", myList.ToString());
console.log("List: ", myList);
console.log("List.ToArray(): ", myList.ToArray());
console.log("List.Contains('ciao'): ", myList.Contains("ciao"));
console.log("List[0]: ", myList[0]);
console.log("List.ElementAt(1): ", myList.ElementAt(1));
console.log("List.elementAt(-1): ", myList.ElementAt(-1));
console.log("List.ElementAt(-5): ", myList.ElementAt(-5));
console.log("List.IndexOf('ciao'): ", myList.IndexOf("ciao"));
console.log("List.IndexOf('ciao', 1): ", myList.IndexOf("ciao", 1));
console.log("List.IndexOf('ciao', 1, 2): ", myList.IndexOf("ciao", 1, 2));
console.log("List.IndexOf('ciao', 1, 3): ", myList.IndexOf("ciao", 1, 3));
myList.Add("!");
console.log("List.Add('!'): ", myList);
